# Generated by Django 3.2.4 on 2021-06-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wish',
            table='wishes',
        ),
    ]
