# Generated by Django 3.2.4 on 2021-06-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_food_discount'),
        ('wishes', '0003_alter_wish_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.food'),
        ),
    ]
