# Generated by Django 3.2.4 on 2021-06-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
