# Generated by Django 3.2.4 on 2021-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_food_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
